### ISSUE TITLE
🎨 [Design] : MVE 3 : Design: Campaign Preview for Admins

### ISSUE THREAD

**Issue by nielskijf** [input-output-hk/catalyst-voices#1005]
### Summary
Improve product demos and/or internal testing by having a mechanism to set and preview the currently active campaign event(s) within the frontend, to avoid annoyances of waiting for specified dates/times to pass. 

### Description
An admin panel with campaign preview controls that can be accessed by campaign "super admins" in any product segment. These controls allow users to switch to a selected campaign phase (as defined by dates set in the campaign builder), preview views for different user authentication states (user, guest, visitor) and roles (voter, proposer, etc.) and switch between the different product segments.

#### User Value
As a **Catalyst developer** or a **Campaign super admin**, I need to preview and test the configured campaign and/or the behaviour of product components moving between different states in relation to the **defined campaign events** and **user authentication states** so I have confidence the campaign and UI will operate as intended.

#### UX Story
When I enter the defined keyboard shortcut, the floating Campaign Preview tool panel should appear on top of all other UI, in the lower left corner. I can close the panel by entering the same keyboard shortcut or pressing the close button.

I want to test the product state, so I click between the Visitor, Guest, Actor segment buttons. 

**Not**
I want to check the views of different actors as defined by the RCAC, so I click the checkboxes or chips of the roles I wish to check, pushed for MVE4.

I want to check specific event dates for the configured campaign. The tool panel displays as list of campaign event phases, and the current stage is labelled. When I click a different stages, the current product segment switches to 5 seconds (or a defined interval) before the target phase. The panel counts down before transitioning into the target phase. By using 'next' and 'previous' buttons I can switch between the next and previous campaign phases with the same effect. A text field allows me to set the timing of the lead-in interval in seconds.

Things that are updated using the Campaign Preview tools are on-page components (mve3). For MVE3 we limit ourselves to three events.

**Later**
Later we might want to switch our pages, and menus based on states.

## State requirements
- [ ] We are pulling the states which current only can be switched from Discovery [home](https://voices.dev.projectcatalyst.io/m4/discovery), in the campaign preview - views tab.
- [ ] Visitor, routes user to Discovery Homepage (visitor state)
- [ ] Guest, routes user to Discovery Homepage (guest view) - probably an empty page - with one state labels currently in DIscovery home.
- [ ] Actor, put the current space in unlocked mode.

## Prev/Next requirements
- [ ] Prev/next toggles through the event listers.
- [ ] Giving the active lister and little 'Active label'

## Spaces switch icons
- [ ] If the admin switches spaces we see the same campaign detail header with the same cards for the Discovery, Voting and Funded project space, once more detail is added in, we can differentiate cards and content.
- [ ] if no page if available for a specific state put in the Discovery homepage page with the correct state, so we can start building this out.

##later
- [ ] -5s, is the time before event is activated, so you can we see the information in the card switch. Due the simplified nature Before, During, After campaign this currently doesn't hold much value.

#### Should
- [x] Be a floating panel, accessible across all product segments
- [x] Only available as a SuperAdmin and Admin
- [x] Open and close via a keyboard shortcut or 'close' button
- [x] Display list of campaign phases (inc. a pre-campaign phase)
- [x] Define a 'lead-in' timing interval
- [x] User State switch: Visitor/Guest/Actor

#### Should not
- [x] Display full dates and times for all events

#### Additional Guidance
- [x] For MVE3 we take a minimalistic approach, and only use before, during, after campaign information cards that populate the respective spaces, see ticket https://github.com/input-output-hk/catalyst-voices/issues/1180 for details. 

Figma design: BDA - [Campaign Preview for (Super)Admins](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--Minimal-Valuable-Experiments-(MVE's)?node-id=7860-111481&t=UkYra33FEDsXFBXw-4)

**Comment by b-farrington** [comment]
Updated the ticket based on co-design feedback and a productive conversation with Niels this morning. I've specified that it really refers to two (related) components that address different needs for two user types and detailed them separately — as well as experimenting a bit with the issue template itself. @nielskijf Thoughts?

**Comment by b-farrington** [comment]
Updated the ticket again, based on further process improvements and scope refinement with Niels. Removed description of a user-facing timeline component as this can be added as a separate ticket. Also removed description of example on-page components, as this is now covered by #1048

**Comment by b-farrington** [comment]
The campaign preview tools panel designed as per the updated ticket (→ [Figma](https://www.figma.com/design/67BnEDUTGw6tSVjAystEG1/(Co)Design-Action-labels?node-id=8729-141569&node-type=instance&t=MN9ETzqGohiC0d31-11))
<img width="300" alt="Screenshot 2024-10-28 at 10 26 46" src="https://github.com/user-attachments/assets/a648815d-bc0b-4736-ac09-a0a64c14e5c4">

Simple click-through prototype demonstrating intended functionality defined [here](https://www.figma.com/proto/67BnEDUTGw6tSVjAystEG1/(Co)Design-Action-labels?page-id=8529%3A93474&node-id=8685-147653&node-type=frame&viewport=-10833%2C-1992%2C0.44&t=8aI9tO3fNGBDPI0x-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=8685%3A147653&show-proto-sidebar=1)

Core component defined in the UI kit [here](https://www.figma.com/design/1e1MMDXyi0oL9sG9IunWL7/UI-Kit-Figma-for-catalyst?node-id=4300-116497&node-type=section&t=jfmlKZ4EJBvODxyn-11). This contains several sub-components ('building blocks') and otherwise uses standard components from the UI kit.
