### ISSUE TITLE
🛠️ [TASK] : Optimize the `sign` function

### ISSUE THREAD

**Issue by apskhem** [input-output-hk/catalyst-voices#1025]
### Summary

Find a way and optimize the `sign` function as it causes lagging on the frontend side.

### Description

Regarding the lagging issue linked to [compression](https://github.com/input-output-hk/catalyst-voices/issues/972). we reviewed the process again after the problem was [addressed](https://github.com/input-output-hk/catalyst-voices/pull/1020). While the performance issue has improved, there are still noticeable lagging in the user experience that might caused from other functions.

As we inspected, we found that the problem caused from the `sign` function. And we need to find a way to remedy this issue.

![Screenshot 2024-10-17 at 14 26 43](https://github.com/user-attachments/assets/f29129a5-9537-4654-a558-4ac3e3f73f11)

In the initial inspecting, we found that this function causes approx. 150ms lagging (blocking).

**Comment by dtscalac** [comment]
Closed, key derivation was identified as much bigger problem compared to the sign function. The key derivation will be optimized in #1012
