### ISSUE TITLE
🎨 [Design] : MVE3: Design superadmin access panel

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1052]
### Summary

Admin access panel

### Description

As an admin, I need a way to access the treasury space, so that I can setup and configure campaigns.

In the future, we will have on-chain admin registration like other user types. Until then, internal users will be the only admins, and will use secret API key(s) to access admin functions, in a way that functions similar to the overall RBAC / permissionless auth for the platform. Admin will need a page they can easily access where they can enter this key and access the treasury space, but this page should not be viewable / discoverable by end users.

AC:
- Build hidden page and recommend entry point
- Build component to input admin key
- Design flow from admin landing as guest in discovery space to accessing treasury space
- Consider splitting technical vs nontechnical admin access (ie configure vs detail)
- Validate approach with architects
- Validate approach with admin team

Related tasks (to be created):
- Understand admin API key requirements
- Generate API key(s) for internal admins
- Integrate admin API key(s) with RBAC / permissionless auth

**Comment by b-farrington** [comment]
Updated the prior draft design to incorporate key visibility toggle in the input field and clarified intended behaviour around key validation, including indication of loading/processing state after user clicks 'save' ([Figma](https://www.figma.com/design/67BnEDUTGw6tSVjAystEG1/(Co)Design-Action-labels?node-id=8905-135456&node-type=section&t=Db4P8dtm74gaxM70-11)). Detailed component [placement](https://www.figma.com/design/67BnEDUTGw6tSVjAystEG1/(Co)Design-Action-labels?node-id=8905-145887&node-type=frame&t=Db4P8dtm74gaxM70-11) (in a neutral / empty page) and a basic user [flow](https://www.figma.com/design/67BnEDUTGw6tSVjAystEG1/(Co)Design-Action-labels?node-id=8905-135457&node-type=section&t=Db4P8dtm74gaxM70-11). Ready for review.

**Comment by mike-mcnulty** [comment]
@nielskijf @b-farrington anything outstanding here or design ticket can be closed?
