### ISSUE TITLE
🎨 [Design] : MVE 3 : Overall Spaces Menu

### ISSUE THREAD

**Issue by nielskijf** [input-output-hk/catalyst-voices#1058]
### Get to do
- [x] Clear notes in figma 'Overall space menu' , and bring to there respective place in Github

### Summary
The overall spaces menu is the 'Cockpit overview' of a brand and its spaces. For MVE 3 - Setup, Detail, Browse Campaigns, we focus on the discovery and workspace, and we show the treasury space if the back-end is configured for an Admin role.

### Description
The Overall Spaces menu is the jump of board of the application. Here people context-switch and choose their next action. Want to comment on draft proposals you jump into the Discovery Space / Browse draft proposals. Want to continue on writing your 1 individual proposal, you jump into your workspace by Click my First proposal.

#### Admin/User Value
_Admin Value_
If a Admin configuration is present the Treasury Space panel is shown, allowing them to open the one campaign for mve3.

_Operations team Value_
Being able to setup a campaign (Super Admin) and detail a campaign (Admin) allows us to setup a workflow, that gives us flexibility and speed to configure a campaign, without having to build interfaces for everything we need to configure.

_User Value_
Having all major actions in one overview creates an holistic overview of the application, and guides people in what they want to do, and what they were doing.

#### UX Story
By opening the Overall Space menu (Only 

#### Requirements
_General_
- [ ] The overall spaces menu is only available in unlocked mode. Currently the Overall spaces menu can also be opened in Guest mode (This should not be possible for privacy reasons.)
- [ ] The minimal configuration of the spaces menu is based on the state: Actor unlocked, as guest and visitor states push users back the discovery space in the respected state configuration.
- [ ] Treasury panel in the Overall Spaces menu is not shown by default.
- [ ] Show treasury panel only with correct back-end admin setup
- [ ] We have no updates for the voting space in this mve, so that one is greyed out.
- [ ] We have no updates for the funded projects space in this mve, so that one is greyed out.

_Discovery space panel_
- [ ] Discovery homepage bring is the the current discovery homepage (actor/unlocked) - This will be build out with multiple campaigns and other segments in the future.
- [ ] If the user click Browse Draft proposals, the user is redirected towards homepage/proposal overview template as indicated [here](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--Minimal-Valuable-Experiments-(MVE's)?node-id=7860-111725&t=LK3H58xsdV6Z9qE0-4).

Figma Component: [Overall space Menu](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--Minimal-Valuable-Experiments-(MVE's)?node-id=7860-111469&t=LK3H58xsdV6Z9qE0-4)

Discuss
- [ ] In the future this is also where you can switch brands, and create a same view of your participation on other brands.
- [ ] I would like to pull the overall spaces menu access in an actionbar that spans across spaces. This would allow for seamless navigation, and makes the purpose of the hamburger menu of spaces themselves more distinct. 
- [ ] We also need to consider a Keyboard shortcut, only active in Actor/Unlocked state.

**Comment by b-farrington** [comment]
Detailed the expected menus for MVE3 [here](https://www.figma.com/design/67BnEDUTGw6tSVjAystEG1/(Co)Design-Action-labels?node-id=9024-135709&node-type=section&t=4DCTDumW6bi6yFTg-11), as best I can from what I can understand from the ticket.

I don't believe the menu is / should be accessible to visitors/guests so have ignored that requirement. The other 'unmet' requirement is actually covered better by #1059 

Have dropped these into the main MVE3 layout page. Ready for review.
