### ISSUE TITLE
🎨 [Design] : MVE 3 : Call to actions in top navigation across spaces

### ISSUE THREAD

**Issue by nielskijf** [input-output-hk/catalyst-voices#1059]
### Summary
Button(s) in the top app bar that highlight the main call-to-action(s) within each product segment for a given user type.

### Description 
The top app bar should contain button(s) that allow a user to initiate the main call-to-action within the current product segment. These CTA buttons will depend on the roles have assigned (but for MVE3 we focus only on **Super Admin** and **Voter** roles).

### Acceptance Criteria

Support the following CTAs in the corresponding product segments:
- [x] Campaign Builder: [Super Admin] 'Save Campaign' (save edits, close open campaign and navigate to ???)
- [x] Discovery Space: [Guest] 'Unlock' (trigger welcome back password modal)
- [x] Discovery Space: [Visitor] 'Get Started' (trigger create new Catalyst keychain modal)
- [x] Discovery Space: [Proposer] 'Submit Proposal' (open New Proposal Modal)
- [x] Discovery Space: [Voter] _none?_
- [x] Workspace: [Proposer] 'Save & close' (save edits, close open proposal and navigate to ???)
- [x] Voting Space: [Voter] 'Submit votes' (initiate vote transaction with current contents of the user's vote list)
- [x] Funded Project Space: [Voter] _none?_

### To consider later
- Responsive controls container with dynamic contents that can be changed per product segment ('space')

---

<details><summary>Original Ticket Draft</summary>
<p>

#### Summary

- Identify which primary call to actions are needed.

#### Description

- For Proposers/Drep 'Get started → Start proposal' after account creation.
- Think through CTA's for other spaces (unlocked)
- Start little table/matrix for other states (no detailing)

</p>
</details>

**Comment by b-farrington** [comment]
Updated the ticket to add clarity. [Outlined a set](https://www.figma.com/design/1e1MMDXyi0oL9sG9IunWL7/UI-Kit-Figma-for-catalyst?node-id=4452-21160&node-type=section&t=Y5otd4vok7Uwixvx-11) of top app bars, using tweaks to the existing component to support the defined CTAs using the existing component. Will copy over to the MVE3 design files.

**Comment by b-farrington** [comment]
Detailed a [suggested rework](https://www.figma.com/design/1e1MMDXyi0oL9sG9IunWL7/UI-Kit-Figma-for-catalyst?node-id=4452-20912&node-type=section&t=Y5otd4vok7Uwixvx-11) of the top app bar component that would allow better flexibility allow us to dynamically adjust sets of contextual controls or buttons. To consider for future MVEs / MVP.
