### ISSUE TITLE
🎨 [Design] : MVE 3 : Discovery Space : Homepage : Discover Campaign Details (Modal)

### ISSUE THREAD

**Issue by nielskijf** [input-output-hk/catalyst-voices#1069]
### Summary
A modal that contains a full description and all details of a specific Campaign, which can appear across product segments (e.g. Discovery Space, Voting Space). Includes full descriptions of each funding category within the campaign.

#### User Value
As a Proposer I want to be able to view the full details of an active campaign, including the funding categories so I can align my idea with the objectives of the campaign and choose an appropriate category in which to submit my proposal.

As a Voter I want to be able to view the full details of an active campaign, including the funding categories so I can remind myself of the objectives of each category I order to inform my proposal evaluation and decision-making process.

#### Requirements
Modal contents should include — in `MVE3`
- Campaign 'Hero' Image_  `later`
- Campaign Title
- Campaign Description
- _Campaign Requirements_  `later`
- Campaign Dates: Start, End
- _Campaign Next Milestone/Deadline_ `later`
- Campaign Categories Count
- Proposals Submitted Count
- _Campaign Total Fund/Treasury_ `later`
- _Campaign Min. Proposal Ask_ `later`
- _Campaign Max. Proposal Ask_ `later`
- _Campaign Funds Requested_ `later`
- Campaign Category Names
- Campaign Category Descriptions (all sections)

Modal controls should include — in `MVE3`
- Close Modal
- Toggle Modal Section Collapse/Open
- Select Campaign Category to view details
- 'Start Proposal' CTA (using currently viewed Category)
- _Favourite/Follow Campaign_ `discuss/later`
- _Share Campaign_ `later`
- _Other (Contextual Menu Dropdown)_ `discuss/later`
- _Previous / Next Campaign_ `later`

Figma Design: [Campaign Details Modal](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--Minimal-Valuable-Experiments-(MVE's)?node-id=7860-111734&t=UkYra33FEDsXFBXw-4)

---
<details><summary>Original Ticket Draft</summary>
<p>

### Summary

The modal that shows campaigns to voters

### Description

[Optimize design](https://www.figma.com/design/67BnEDUTGw6tSVjAystEG1/(Co)Design-Action-labels?node-id=9058-202537&t=2jEH07Q5CQRWmlXi-4)
</p>
</details>

**Comment by b-farrington** [comment]
Updated issue description to reflect recent thinking about this component and associated user needs.

Work designing version of this for MVE3 completed and ready for review.
