### ISSUE TITLE
🎨 [Design] : MVE2 refinement: differentiate chip color in seed phrase confirmation

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1084]
### Summary

differentiate chip color in seed phrase confirmation

### Description

As a user, I need different colors to distinguish used and unused words during seed phrase confirmation, so that I know which words still need to be used.

AC:
- Used and unused chips for seed phrase words are different from each other
- Review designs with team and handoff for development

**Comment by b-farrington** [comment]
Explored a few [quick fixes](https://www.figma.com/design/67BnEDUTGw6tSVjAystEG1/(Co)Design-Action-labels?node-id=9810-119411&node-type=section&t=NBdTOH4z9t24aYYa-11). To update colour palettes coherently we'd need to rework the themes (which while needed, is beyond the scope of this ticket). Suggest simple solution to increase spacing and add horizontal divider for basic fix for now.
