### ISSUE TITLE
🛠️ [TASK] : MVE2 refinement: submit text on enter key

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1085]
### Summary

submit text on enter key

### Description

As a user, I want to to submit my text input when I hit return, so that I do not need to manually click a button to proceed.

Use cases
- Set unlock password
- Unlock application
- Remove keychain

GIVEN a user has completed all required text inputs
WHEN hit 'enter' key
THEN submit form

Open question:
- Is this something that can be globally applied, or need to update every individual instance?

**Comment by dtscalac** [comment]
@mike-mcnulty 

> Is this something that can be globally applied, or need to update every individual instance?

Yes, it has to be updated in every individual instance but it's very straightforward. We can decide that we always want to submit via enter key and we will look out for it.
