### ISSUE TITLE
🛠️ [TASK] : MVE2 refinement: add supported wallets link

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1086]
### Summary

add supported wallets link

### Description

As a user, I want to see the list of all supported wallets in Catalyst, so that I know which options I have for connecting a Cardano wallet to Voices.

GIVEN a user in the "link cardano wallet to keychain" account creation step
WHEN click "see all supported wallets"
THEN launch new browser tab to show supported wallets in [gitbook](https://docs.projectcatalyst.io/current-fund/voter-registration/supported-wallets)

![Image](https://github.com/user-attachments/assets/73857346-1dba-4fda-bf0e-5777794044f8)

**Comment by Henrywilliam96** [comment]
> ### Summary
> add supported wallets link
> 
> ### Description
> As a user, I want to see the list of all supported wallets in Catalyst, so that I know which options I have for connecting a Cardano wallet to Voices.
> 
> GIVEN a user in the "link cardano wallet to keychain" account creation step WHEN click "see all supported wallets" THEN launch new browser tab to show supported wallets in [gitbook](https://docs.projectcatalyst.io/current-fund/voter-registration/supported-wallets)
> 
> ![Image](https://private-user-images.githubusercontent.com/91077234/381733795-73857346-1dba-4fda-bf0e-5777794044f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMzQ5MjMsIm5iZiI6MTczMDMzNDYyMywicGF0aCI6Ii85MTA3NzIzNC8zODE3MzM3OTUtNzM4NTczNDYtMWRiYS00ZmRhLWJmMGUtNTc3Nzc5NDA0NGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAwMzAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ODM5Y2NhMDY0MDRlYWI1MzM5YTgxNmI5NzA4MjliOWFmMjFkOWU2MWIzYTNmMWYzZjkxYTNkMTM0ZTM5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X7nKk6dWVSWccyBTDpb0oiaWbG4itss6trYz8I064X4)


Hey @mike-mcnulty To see the list of all supported wallets in Catalyst for connecting a Cardano wallet to Voices, you can usually find this information on the official Catalyst website or in their documentation. Look for sections related to wallet integration or supported wallets. Common wallets that are typically supported include Daedalus, Yoroi, and Nami. If you’re unable to find the information, consider checking their community forums or reaching out to their support for the most up-to-date details.

**Comment by mike-mcnulty** [comment]
Appreciate you @Henrywilliam96 ! This task is to bring all those great resources you mention directly into the application experience, so that you don't have to go hunting for those docs somewhere else. Are you familiar with what the team is working on with Catalyst Voices?

**Comment by Tao546127REP** [comment]
> Appreciate you @Henrywilliam96 ! This task is to bring all those great resources you mention directly into the application experience, so that you don't have to go hunting for those docs somewhere else. Are you familiar with what the team is working on with Catalyst Voices?


@mike-mcnulty I'm glad you're finding the resources helpful! I’m not specifically familiar with what the team is working on with Catalyst Voices, but it sounds like an interesting initiative. If you have any details or updates on it, feel free to share!
