### ISSUE TITLE
🛠️ [TASK] : MVE2 refinement: choose other wallet clarification

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1087]
### Summary

choose other wallet clarification

### Description

As a user, I want to be able to "choose another wallet" from the wallet details screen, so that I can connect a different wallet before proceeding, if the wallet details are not what I expect. 

AC
- Replace button text "Back" with "Connect a different wallet" on the "wallet detection summary" screen shown after a user successfully connects with the wallet extension
- Remove option "choose other wallet" on the role selection screen. Reasoning is that "choose different wallet" makes more sense when I'm confirming wallet details, not when I'm choosing which roles to associate with my connected wallet. 

![Image](https://github.com/user-attachments/assets/3df848ba-cc5f-4250-8ddd-86aad2860386)

![Image](https://github.com/user-attachments/assets/c93acbfa-ede7-4a87-b6b6-445c46c29373)

Open question:
- Useful to have design task first to show changes, or clear enough from ticket?

**Comment by dtscalac** [comment]
It's clear enough from the description, though design should be updated as it acts as a documentation.
