### ISSUE TITLE
🛠️ [TASK] : MVE2 refinement: add info text to waiting screen

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1088]
### Summary

add info text to waiting screen

### Description

As a user, I want to review my role registration transaction before signing, so that I have confidence in what I'm submitting to chain. 

AC
- Update button CTA copy
   - OLD: "confirm & sign with wallet"
   - NEW: "Review registration transaction"

![Image](https://github.com/user-attachments/assets/7ff63507-92e7-467c-a0d6-c4f5644dbea2)

**Comment by LynxLynxx** [comment]
@mike-mcnulty Where exactly would you like to see this text  "Please wait while we build your role registration transaction and calculate network fees" under title "Let's make sure everything looks right." or mayby in the center above Circular progress indicator?

**Comment by dtscalac** [comment]
@nielskijf can you sketch some design for this?
