### ISSUE TITLE
🛠️ [TASK] : Implement admin campaign preview tool widget

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#1113]
### Summary

Implement admin preview tool widget

### Description

As an admin user, I need a preview tool widget, so that I can see how my draft campaign will look to different users at different times across spaces (before I publish it).

See related design task for additional context #1005 

AC
- Keyboard shortcut to launch preview tools
- If user clicks the stages tab within the control window, then show list of campaign stages
   - Before campaign start
   - During campaign
   - After campaign ends
- If user clicks campaign stage, then change spaces components to reflect that stage
- If user clicks the views tab within the control window, then show application states
   - Visitor (no key)
   - Guest (key found, locked)
   - Active (key found, unlocked)
 - If user clicks application state, then change spaces components to reflect that state

Out of scope (future MVE)
- More granular campaign stages control to reflect all stages in campaign timeline (proposals, voting)
- More granular views control based on registered roles (voter, proposer)
- Option to toggle mock data on / off within space

**Comment by dtscalac** [comment]
Keyboard shortcut: ctrl+shift+A.

Can be easily changed if we need to.
