### ISSUE TITLE
🛠️ [TASK] : Proposal overview - no proposals -  empty state

### ISSUE THREAD

**Issue by nielskijf** [input-output-hk/catalyst-voices#1182]
### Summary
When I campaign launches, there is probably a 'short' window in which there are no draft proposals in the Discovery Space / proposal overview page. (Actor Unlocked)

## Description / User story
As a user, I want a clear indication of an empty state, so I can be certain that there are no published draft proposals published yet.

## Requirements
- [x] Implement the dark/light empty state for Discovery Space / Draft propoposal (Actor Unlocked)

Figma: [Proposal overview - empty state](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--Minimal-Valuable-Experiments-(MVE's)?node-id=7860-111632&t=cqdIZBDVOkl9q7HA-4)

**Comment by dtscalac** [comment]
@LynxLynxx please make the empty state widget reusable so that we could reuse it in #1195
