### ISSUE TITLE
🛠️ [TASK] : Schema mismatch Integration test for `cat-gateway`

### ISSUE THREAD

**Issue by Mr-Leshiy** [input-output-hk/catalyst-voices#204]
### Summary

Add an integration test for schema mismatch case for `cat-gateway`

### Description

Need to add an integration test for checking schema mismatch case for `cat-gateway`

**Comment by kukkok3** [comment]
I think this is covered already by https://github.com/input-output-hk/catalyst-voices/pull/226 ?

**Comment by saibatizoku** [comment]
> I think this is covered already by #226 ?

Nope, I'm adding a branch in a moment, the test specifically focuses on changing the schema version while the cat-gateway is active, to test the expected behaviour.
