### ISSUE TITLE
🏛️ [EPIC] : [V1]  Proposal form builder 

### ISSUE THREAD

**Issue by minikin** [input-output-hk/catalyst-voices#216]
## Summary

The Proposal Form Builder is an innovative tool that revolutionizes applications' handling of forms. Aiming to enhance developer experience and end-user interaction, this tool dynamically creates forms based on JSON data inputs.

## JIRA Epic

https://input-output.atlassian.net/browse/NPG-8834

## Introduction

The Proposal Form Builder is an innovative tool that revolutionizes applications' handling of forms. Aiming to enhance developer experience and end-user interaction, this tool dynamically creates forms based on JSON data.

## Key Features

- **JSON-Driven Architecture** 
The form builder consumes JSON data to generate forms dynamically. This allows for a high level of customization and flexibility in form design, as changes to the form can be made simply by altering the JSON input.

- **Adaptive Form Fields** 
Capable of creating a wide range of form fields such as text inputs, radio buttons, checkboxes, dropdowns, and more. The adaptive nature of these fields ensures that the form can cater to diverse data input requirements. The initial inventory will be provided in the tasks list.

## Out of scope for V1

- **Real-Time Preview** 
Developers or administrators can build and view a real-time preview of the forms as they are being built, allowing for immediate feedback and adjustments.

- **Validation and Error Handling** 
Incorporates robust validation rules and error-handling mechanisms to ensure data integrity and user input accuracy.

### Backend

- [ ]  #224

### Frontend

- [ ]  #234
- [ ]  #233

### Supporting Tickets

- [x] #240
- [x] #218
- [x] #249

**Comment by minikin** [comment]
@mike-mcnulty @stevenj

**Comment by mike-mcnulty** [comment]
@minikin is this ticket still relevant given our most recent discussions on how campaign builder should work?

**Comment by Mr-Leshiy** [comment]
not relevant anymore
