### ISSUE TITLE
🛠️ [TASK] : Revisit `cat-gateway` integration test

### ISSUE THREAD

**Issue by bkioshn** [input-output-hk/catalyst-voices#238]
### Summary

Revisit `cat-gateway` integration test

### Description

`health_live` integration test is now being ignored from the `test` pipeline. 
This is because the`cat_gateway_address` is invalid and causes workflow to fail.

https://github.com/input-output-hk/catalyst-voices/blob/main/catalyst-gateway/tests/integration/catalyst_gateway_event_db.rs

One possible solution may be to move this integration test to other places, so it will not execute during common Rust test procedure

**Comment by kukkok3** [comment]
This test can be deleted as it was just an example

**Comment by bkioshn** [comment]
> This test can be deleted as it was just an example

Shoud this be deleted now? maybe leave it like this just for reference @kukkok3

**Comment by kukkok3** [comment]
I will do it as part of another PR I'm already working on:)
