### ISSUE TITLE
Create figma prototype for minimally functional proposal module (M2)

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#244]
In order to complete [Milestone ](https://fund10.catalystcats.io/our-catalyst-proposals/iog-catalyst-team-ideascale-replacement-and-web-browser-based-voting-centre-with-liquid-democracy/iog-catalyst-team-deliverables-outputs-and-intended-outcomes-of-each-milestone)2 for Catalyst Voices, we must satisfy the following item:

“Deploy minimally functional proposal module to testnet for refinement over course of project”

As a user, I need to be able to view & edit the proposal template, so that I can submit my ideas for a chance to win funding. Once I have created a proposal, I expect to see it in the overall Proposal List, so that others can find my idea & provide feedback.

Screen1:

- Basic site header
- Empty list of proposals
- “Add proposal” button

Screen2:

- Proposal editor header
- Clickable anchors on left navigation rail
- Editable fields in the main working space
  - Title | String | 60char limit
  - Problem | String | 140char limit
  - Solution | String | 140char limit
- Save button

Screen3:
Same as screen1
Proposal list contains the one just created

Acceptance criteria:
Screens created, reviewed, and handed off for development

**Comment by mike-mcnulty** [comment]
Tasks to refine prototype after review with team:

1. Simplify splash to only the final panel with “impactful projects" header
2. Remove anchors & toggle from left navigation menu
3. Remove metadata section
4. When change status to publish, then return user to proposal list

**Comment by nielskijf** [comment]
Problem | String | 140char limit
Solution | String | 140char limit

Character limit is 200 for both.

**Comment by mike-mcnulty** [comment]
Initial prototype completed & ready to pick up for future iterations on the flutter app. Will not be developed as part of Milestone 2, due to lack of flutter engineer capacity. Instead, M2 will be simplified to only include the splash screen as described in this ticket: https://github.com/input-output-hk/catalyst-voices/issues/274

@nielskijf @minikin @stevenj
