### ISSUE TITLE
[DESIGN] Campaign Builder / Treasury Setup

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#284]
As an admin user, I need to be able to define treasury details for an event, so that my community has an incentive to engage & understands the rules governing the campaign budget. 

GIVEN a user inside campaign editor
WHEN expand the "Treasury" section
THEN show all relevant data fields:

- [x] Currency Denomination
- [x]  Total Budget
- [x]  Grant Budget
- [x]  Reward Budget

Additional details on fields, description, sample values, user input type, and data validations [here](https://docs.google.com/spreadsheets/d/126j88a9Zo1ghbdJonB_P8BG4-8OvO-94_Qbk0oOW4UI/edit#gid=1506329189). 

AC:
- Treasury Setup includes all relevant questions and ability to input responses
- Prototype draft completed
- Review prototype with stakeholders from admin team to ensure process viability
- Review prototype with engineering team to ensure feasibility
- Prototype ready for user testing

**Comment by mike-mcnulty** [comment]
FYI @coire1

**Comment by nielskijf** [comment]
Latest 2 parameters in segment 7 or 8. Sync.
