### ISSUE TITLE
[DESIGN] Campaign Builder / Voting Rules

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#287]
As an admin user, I need to be able to set rules about voting, so that I can control who can vote and how votes will be counted.

GIVEN a user inside campaign editor
WHEN expand the "Voting Rules" section
THEN show all relevant data fields:

- Voter Min Token Holding
- Voting Power Calculation
- Voting Options
- Voting Privacy
- Allow Dreps?
- Proposal Funding Logic
- Proposal Acceptance Threshold
- Tally Committee Selection Method

Additional details on fields, description, sample values, user input type, and data validations [here](https://docs.google.com/spreadsheets/d/126j88a9Zo1ghbdJonB_P8BG4-8OvO-94_Qbk0oOW4UI/edit#gid=1506329189).

AC:

- Voting Rules Setup includes all relevant questions and ability to input responses
- Prototype draft completed
- Review prototype with stakeholders from admin team to ensure process viability
- Review prototype with engineering team to ensure feasibility
- Prototype ready for user testing

**Comment by mike-mcnulty** [comment]
FYI @coire1

**Comment by nielskijf** [comment]
All items are used, but ended up in different segments. Let's align segment names and parameters.
