### ISSUE TITLE
:hammer_and_wrench: [TASK] : Campaign Builder / Campaign Templates

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#288]
IN SCOPE

As an admin user, I need to be able to set the proposal questions required by a category, so that I can crowdsource the types of proposals I want to see in my campaign. This should be defined via JSON (include field descriptions and data validations) in the MVP.

GIVEN an admin user in campaign editor
WHEN select existing OR upload new category template
THEN apply selected template as category question template for that event 

Note: entire proposal template will be defined for each category. In future state, will have option to easily inherit questions from other categories, so it's easy to edit just the sections that differ across them.

Todo:
- [x] Upload base category-question.json
- [x] Setup base category milestones
- [x] Base Funded Projects Agreements select

Questions NK:
- Above is configuration is json, we most not turn the campaign builder in a full cms ;)
- I would see a template as a fully configured Voting event that has run successfully and is closed?
- We might want to start thinking about a Treasury / Brand Manager product segment, in which these things are setup.
- We are reaching scope creep. MVP Y/N.

AC:
- Template Selection added to Campaign Editor
- Discussion with engineering team to align on remote widget approach vs alternatives, in order to serve both short and long term needs
- Prototype draft completed
- Review prototype with stakeholders from admin team to ensure process viability
- Review prototype with engineering team to ensure feasibility
- Prototype ready for user testing

OUT OF SCOPE

As an admin user, I need to be able to select templates for proposals, categories, and milestones, so that I can control the questions answered by different types of proposers.

GIVEN an admin user in campaign editor
WHEN select proposal template
THEN apply selected template as base proposal template for that event 

GIVEN an admin user in campaign editor
WHEN select milestone template
THEN apply selected template as milestone question template for that event

**Comment by mike-mcnulty** [comment]
FYI @coire1

**Comment by nielskijf** [comment]
@mike-mcnulty Do you have some guidance on what kind of 'Base Funded Projects Agreements select' we are expecting, it's like ToS agreement checkbox for PoA, SoM's?

**Comment by mike-mcnulty** [comment]
TODO: align with @minikin on remote widget approach and reconcile requirements; likely UX = select remote widget from dropdown, preview how widget will render, and confirm (as an admin user inside campaign builder)

TODO: move funds agreement selection into #317

**Comment by mike-mcnulty** [comment]
@nielskijf let's revisit this one
