### ISSUE TITLE
:hammer_and_wrench: [TASK] : Discovery Space / View Campaign Details

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#313]
As a user, I want to view all the details about a campaign in a single location, so that I can learn all required context before participating.

GIVEN campaign parameters defined in builder
WHEN publish new campaign
THEN users can see all details about campaign in one location

GIVEN a user navigating the Catalyst brand
WHEN click on "Events"
THEN see overview of all published events
AND WHEN click on an event
THEN see all details about selected event

AC:

- Campaign details page designed & component created, borrowing from proposal detail component
- Prototype draft completed
- Review prototype with stakeholders from admin team to ensure process viability
- Review prototype with engineering team to ensure feasibility
- Prototype ready for user testing

**Comment by nielskijf** [comment]
Let's do a co-design session for this, and schedule this for the Discovery space. As the user facing part needs more visual design, and not all data is needed in the front-end, or needs additional copy. Content first?
