### ISSUE TITLE
🛠️ [TASK] : Collect test coverage for Dart code

### ISSUE THREAD

**Issue by minikin** [input-output-hk/catalyst-voices#373]
### Description

- [ ] Collect test coverage for Dart code in `catalyst_voices`, `packages`, and `catalyst_voices_packages`
- [x] Add/Update  step to run static analysis checks for all packages
- [x] Add/Update  step to run format-check for all packages and fail if it doesn't match
- [x] Update CI/CD jobs

### Notes

- consider utilizing [melos](https://github.com/input-output-hk/catalyst-voices/blob/main/melos.yaml ) for Dart/Flutter related tasks 
- [Earthfile](https://github.com/input-output-hk/catalyst-voices/blob/main/catalyst_voices/Earthfile) to update

Consult with @kukkok3 about publishing test coverage results.

**Comment by dtscalac** [comment]
In this task we started to generate coverage reports however they will be uploaded to codecov in #407
