### ISSUE TITLE
🛠️ [TASK] : Upload test coverage for Dart code to coveralls

### ISSUE THREAD

**Issue by dtscalac** [input-output-hk/catalyst-voices#407]
### Description

- [ ] In #373 flutter packages started to generate coverage reports, upload them to [codecov](https://coveralls.io/).

### Notes
- Inspect `test-report` script in `melos.yaml` to learn about the coverage generation.

**Comment by dtscalac** [comment]
@minikin Here is the task for codecov, will you be working on the the codecov replacement tool?

**Comment by minikin** [comment]
@dtscalac,feel free to pick it up. However, instead of codecov we will be using https://coveralls.io/. L
