### ISSUE TITLE
🛠️ [TASK] : Controlled DB Migrations for `cat-gateway`

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#45]
### Summary

Setup deployable and controlled database migrations for the DB

### Description

Database migrations must not be automatic and must be a different step, although they can be included in the same container and triggered with a different entry point.

**Comment by Mr-Leshiy** [comment]
depends on #82

**Comment by Mr-Leshiy** [comment]
Already solved in https://github.com/input-output-hk/catalyst-voices/issues/82
