### ISSUE TITLE
🛠️ [TASK] : `cat-gateway` health endpoint to probe schema version

### ISSUE THREAD

**Issue by stevenj** [input-output-hk/catalyst-voices#47]
### Summary

Ensure that if the schema version changes during runtime, the service stops serving traffic.

### Description

Every time a health endpoint is checked, the DB schema version should be validated, and if it is not the version the service expects, the service needs to suspend until it is correct.

- [x] Add state variable for keeping track of the schema version validation status.
- [ ] Add poem middleware to disable service when there is a schema version mismatch.

**Comment by minikin** [comment]
@saibatizoku Please, add info on why this blcoked.
