### ISSUE TITLE
🛠️ [TASK] : Discovery Space MVE Mocked UI

### ISSUE THREAD

**Issue by dtscalac** [input-output-hk/catalyst-voices#736]
### Summary

Mocked Discovery Space Screen

### Description

Development of Discovery Space screen
- [Figma](https://www.figma.com/design/80aDAQgoD0v06DO2Sb76ok/Catalyst--Minimal-Valuable-Experiments-(MVE's)?node-id=5131-26729&t=0uylSOBxY9pPUO6V-4)

Part of #726

**Comment by damian-molinski** [comment]
UI Kit example was merged in #711
