### ISSUE TITLE
🛠️ [TASK] : Link staking key & signing key with keychain

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-voices#797]
### Summary

Add wallet & roles to keychain. Link staking key & signing key with keychain

### Description

Parent #727 

Users will submit a transaction to Cardano mainnet in order to establish a verifiable link between their on chain identity (staking key) and dapp identity (master signing key). In future iterations, a similar transaction will be used to link additional keys like encryption keys or role specific keys. 

Transactions should be built according to the RBAC metadata standard and signed by master signing key in the user's local vault. The app will send that transaction body, signed by the master signing key, to the wallet browser extension. There, users will sign the transaction with their wallet's staking key, and submit to Cardano mainnet. 

GIVEN a user with a master signing key in the local vault
WHEN user click 'confirm and sign with wallet'
THEN application build tx AND sign with signing key
AND THEN send tx to wallet
AND WHEN recieve success response from wallet that tx submitted
THEN send tx metadata to backend for temporary storage until tx confirmed on chain

#### Docs

- [Registration 1/5](https://github.com/cardano-foundation/CIPs/pull/810/files#diff-d540ac79d44362bffd57b3eea1396db738ca813733c9e84fa6518d9cbebf6b03)
- [Registration 2/5](https://github.com/cardano-foundation/CIPs/pull/811/files) 
- [Registration 3/5](https://github.com/cardano-foundation/CIPs/pull/812/files#diff-4ffe445f8e72a6cee701a5a989aef62750d96c6296058bb612cad8ff305b49a5)
- [Registration 4/5](https://github.com/cardano-foundation/CIPs/pull/813/files#diff-4ffe445f8e72a6cee701a5a989aef62750d96c6296058bb612cad8ff305b49a5)
- [Registration 5/5](https://github.com/cardano-foundation/CIPs/pull/814/files#diff-4ffe445f8e72a6cee701a5a989aef62750d96c6296058bb612cad8ff305b49a5)

Questions:
- what is the specific metadata standard that will need to be used to build transaction?
- will user need to enter device unlock password prior to sending tx to wallet, so that app can sign with master signing key?

**Comment by dtscalac** [comment]
> what is the specific metadata standard that will need to be used to build transaction?

RBAC defined here: https://raw.githubusercontent.com/cardano-foundation/CIPs/95504783ef031ab7f95c33ee5d51f71de06ad04f/CIP-XXXX/images/metadata-envelope-process.svg


> will user need to enter device unlock password prior to sending tx to wallet, so that app can sign with master signing key?

No, keychain is unlocked during registration, no need to unlock it. Currently the app doesn't supporting restoring the registration, i.e. if user left in the middle then the user must restart from the beginning. In the future when we want to restore already started registration (i.e past creating keychain) then we might need to ask the user to unlock the keychain.
