### ISSUE TITLE
🛠️ [TASK] : Keychain

### ISSUE THREAD

**Issue by damian-molinski** [input-output-hk/catalyst-voices#813]
### Summary

Development of Keychain 

### Description

Part of #796 

- [x] #876
- [x] #1012

- Requires **master key**.
- Encapsulates different keys and takes care of creating different keys from **master key** (key derivation). 
- Later will be able to add more keys.

**Comment by dtscalac** [comment]
Issue for @apskhem :)

**Comment by stevenj** [comment]
This is pre-mature.
We do not have comprehensive specifications for all the key derivation we require yet, and currently it is not required.
All that is required is to generate a single Ed25519 Private/Public key paid from the seed phrase, and use that for a role 0 key.
All that needs to happen for now is the key phrase be converted to a 256 bit number, which can serve as the temporary Role 0 private key, the public key can be derived from that private key.
Any method that converts the key phrase to the 256 bit value is sufficient for the current use case, which is testing RBAC registration with Role 0 only.

**Comment by dtscalac** [comment]
@stevenj This flutter package [ed25519_hd_key](https://pub.dev/packages/ed25519_hd_key) supports the hard derivation and in that manner is conformant to the rust crate, however it doesn't support soft derivation which is supported by the rust counterpart. Will the soft derivation be needed?

**Comment by bkioshn** [comment]
This [ed25519_hd_key](https://pub.dev/packages/ed25519_hd_key) won't work in Cardano HD.
There is slight different on how it is implemented (see [SLIP-0023](https://github.com/satoshilabs/slips/blob/master/slip-0023.md)). The current derivation would be "Cardano Icarus master node derivation".

**Comment by stevenj** [comment]
Soft derivation is used a lot, in a general sense we should be able to do both.
If there is no pure dart package for it, we may need to fork the library you linked and either contribute back the necessary changes upstream, or just make a forked version we use.
