### ISSUE TITLE
🛠️ [TASK] : Workspace - Segment close behaviour 

### ISSUE THREAD

**Issue by digitalheartxs** [input-output-hk/catalyst-voices#842]
### Summary

Implement Segment close behaviour  for the Workspace / Proposal Editor

### Description
Segments > section > topic(s)
- [x] On load everything is open, and first segment/section is selected.
- [x] There is always one selected section.
- [x] If active segment is closed, the right rail shows - 'Please select an item to show related content'
- [x]  If ALL segments are closed, the right rail shows - 'Please open a segment to show related content'
- [x] If all segments are closed, and the user opens a segment, the first section is selected
- [x] if there is an active section selection, and the user opens segments, only the segment opens, but no active section change.

### scroll behaviour
- [x] Cick on a section scroll the page to that section.

### Edit different section in the mid-rail
- [x] State: No edit open - If the user clicks edit in a different section, the active state moves to that specific section, and the left-menu activates the correct section as well.
- [x] if the user clicks on a different section / edit, and the user has a section already in edit mode, we throw a little pop-up, with the message, please save before editing something else. The pop only states the instruction with an Ok button.

## Later / Parking space
- Free scroll behaviour and relational content. The main value driver of the Workspace / Proposal Editor is Data-in-Context, yet we should not block users to scroll through the mid content rail (desktop), keeping the active section in sync might be difficult, based on screensizes. A simple solution could be an indication 'banner' that says 'Return to education in context', it's a 'Back to top' variant, that selects the first item and starts showing relational content again.
- After this upgrade, we will do further investigation on behaviour.
- We have ideas about text-input and max characters from a writer perspective. (Not being able to type beyond max character is annoying, as you need 'space for innovation', otherwise we push people to other writing tools again, idea stacks is another approach we can investigate.
- Focus mode (post mvp) is a feature that would put all widgets in edit mode, giving writers the opportunity, to steamline their word usage across sections.

**Comment by damian-molinski** [comment]
Blocked by #1165
