### ISSUE TITLE
Redirect /m4 to /m4/discovery

### ISSUE THREAD

**Issue by damian-molinski** [input-output-hk/catalyst-voices#866]

**Comment by mike-mcnulty** [comment]
@damian-molinski i get page not found when I try https://voices.projectcatalyst.io/m4. confirmed on incognito mode as well

![Image](https://github.com/user-attachments/assets/844156be-e4f7-46fa-9fe1-358fb1b610bc)

**Comment by damian-molinski** [comment]
@mike-mcnulty we still don't have automated release process. You can follow issue here #785. Right now Sasha is releasing it manually and we'll need to wait for him to come back. Till then we have to wait
